# Generated by Django 3.2.5 on 2021-08-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
